-- Création de la table d'analyse centralisant les statistiques régionales
DROP TABLE IF EXISTS stock_region_besoin;
CREATE TABLE stock_region_besoin AS

-- Région Tunis
SELECT ANNEE, MOIS, CODE_BESOIN, 'TUNIS' as REGION, 
SUM(COALESCE(STKTUDIPH,0) + COALESCE(STKCOMPT,0) + COALESCE(STKFERME,0) + COALESCE(STKSERUM,0)) as STOCK_REGION,
SUM(COALESCE(VTETUDIPH,0) + COALESCE(VTECOMPT,0) + COALESCE(VTEFERME,0) + COALESCE(VTESERUM,0)) as VENTE_REGION
FROM fact_mouvements GROUP BY ANNEE, MOIS, CODE_BESOIN

UNION ALL
-- Région Sfax
SELECT ANNEE, MOIS, CODE_BESOIN, 'SFAX' as REGION, 
SUM(COALESCE(STKCEPHOP,0) + COALESCE(STKCEPOF,0)) as STOCK_REGION, 
SUM(COALESCE(VTECEPHOP,0) + COALESCE(VTECEPOF,0)) as VENTE_REGION
FROM fact_mouvements GROUP BY ANNEE, MOIS, CODE_BESOIN

UNION ALL
-- Secteur National
SELECT ANNEE, MOIS, CODE_BESOIN, 'NATIONAL' as REGION, 
SUM(STOCK_TOTAL) as STOCK_REGION, 
SUM(VENTE_TOTAL) as VENTE_REGION
FROM fact_mouvements GROUP BY ANNEE, MOIS, CODE_BESOIN;
